### ISSUE TITLE
Migration to an open repository and re-branding

### ISSUE THREAD

**Issue by ceriottm** [epfl-cosmo/i-pi-dev#126]
In the framework of an EU project (that pays @grhawk !) we have to release a beta of "i-PI 2.0" by the end of August so I wanted to discuss (particularly with @OndrejMarsalek ) how to do this properly. In the framework of this change, I also want to propose a change of name, to reflect the increasing number of features that are not PIMD related (geometry optimization, instantons, etc. ) My proposal for a new name is i-MOVE (an interface for moving atoms based on an external force engine) but I am open to suggestions.
So in terms of practicalities of the repository transfer we could do multiple things I think: 
1- create a repo that is a fork of the clean-up branch (or of a post-clean-up-merge master) and then close features and pull requests here and then merge them there
2- clone the full repo and continue the development there 
3- erase history, move there and then open a new restricted set of feature branches, porting code over from here to there in terms of patches. 
or?

**Comment by ipoltavskyi** [comment]
Dear Michele,

This would be great. Right now I am in vacation. But as soon as I will come back I will make all required tests for the new reading/writing infrastructure and continue working on PPI and related stuff. In fact I have found one more thing which can be easily added to i-PI to make it even more useful for users which would like to play with MD/PIMD simulations using there force-field, ML, etc. codes.  

Best wishes
Igor

**Comment by ceriottm** [comment]
OK I guess that several months after we went public this issue can be closed. Of course now the next challenge is v2 release and moving that into the i-pi/i-pi repo
