### ISSUE TITLE
Cholesky decomposition vs Hermitian square root in generalized langevin thermostat

### ISSUE THREAD

**Issue by yantaow** [epfl-cosmo/i-pi-dev#136]
Dear all, 

I'm implementing a gle thermostat in my own code. To extract S from SS^T, the paper (Colored-Noise Thermostats a la Carte) suggested using Cholesky decomposition. However, in the iPi implementation, I saw the following comment and code: 
# Uses a symmetric decomposition rather than Cholesky, since it is more stable

return root_herm(SST)
# return stab_cholesky(SST)

I've tried both, and indeed the Hermitian square root works far better than Cholesky, the latter of which doesn't converge energy at all.  I'm wondering whether you understand why this is the case. In principle, both should work pretty well, but the difference in their practical performance is quite baffling.

Thanks very much! 
Yantao

**Comment by ceriottm** [comment]
I am surprised that you find energy non conserved by the Cholesky
decomposition. With most GLE matrices it should do just fine. Problem is
that Cholesky (even the stabilized version used in the code) gets very
unstable when the input matrix has eigenvalues close to zero. Using an
eigenvalue decomposition allows you to play safe and keep zero eigenvalues
from contaminating other parts of the matrix.
