### ISSUE TITLE
Finite Temperature CellOptimization with Isotopic Species

### ISSUE THREAD

**Issue by abb58** [epfl-cosmo/i-pi-dev#137]
Hi All,

I was wondering if a capability like "finite temperature cell-optimization with isotopic species" exists/feasible in the current state of code (cellopt branch). I had a peak at few snippets related to the cell optimization but couldn't really figure out how one can incorporate treating of isotopic species and/or temperature dependence. It would be great if someone can shed some light regarding this.

Thanks for your time,
-Abhishek

**Comment by ceriottm** [comment]
Well, you can always run NST at finite temperature, and evaluate the
average size of the cell.
If you're thinking of quasi-harmonic approximation, though, you have to do
that manually.
M
