### ISSUE TITLE
Important units problem

### ISSUE THREAD

**Issue by grhawk** [epfl-cosmo/i-pi-dev#147]
We just found an important bug: after the merge with fastxyz the units conversion in input will be applied based on the keyword in the file containing the positions file AND on the keywork in the `initialize` node of the input xml. For example: if the comment in the file contains `position{angstrom}` and the xml contains 
```
<file units='angstrom'> namefile </file>
```
i-PI will convert the position of the atoms twice. The output is not guaranteed to be right!

**Comment by mahrossi** [comment]
Ugh! :( Good catch.

**Comment by grhawk** [comment]
@mahrossi well... I should have seen it before the merge... so it is not a so good catch... :(

**Comment by grhawk** [comment]
In the branch [fix_iounit](https://github.com/epfl-cosmo/i-pi-dev/tree/fix_iounits) the input is working now with the following rules:

- reading the units directly from xyz (pdb) file when is present something like `position{angstrom}`  and `cell{angstrom}` in the comment (title) line.
- if the attribute `units` is specified in the `<file>` node, then it will be applied anyway (this could still result in applying the conversion factor twice but otherwise, we would loose retro-compatibility.) but a warning is printed.
- if the cell is specified in both, the xyz (pdb) file and in the xml: the last one is used (with the relative warning of overwriting the other property). 
- about the output: `xyz` is working fine. `pdb` has some problem that I am trying to track down...

**Comment by grhawk** [comment]
### Still todo:
 - [ ] Check the warning messages they could probably be shorter...
 - [ ] Update the documentation
 - [x] Update the examples
 - [ ] Move the output units conversion machinery into the `io` module
