### ISSUE TITLE
Cannot resume a simulation with LAMMPS

### ISSUE THREAD

**Issue by brunoduran** [epfl-cosmo/i-pi-dev#160]
I have been trying i-PI and unlike LAMMPS vanilla ensembles I cannot split the simulation in several sections, from something like this:

```
fix ipi ...

run 200
```

to something like this:

```
fix ipi ...

run 100

run 100
```

In the second run the simulation halts. I am not sure if this is the expected behaviour, some problem with my software or a bug.

I am working with:

* i-PI 1.0
* LAMMPS (14 May 2016)
* macOS 10.11

**Comment by ceriottm** [comment]
Uhm... we never tried this and in principle I have a hard time seeing when this might 
be useful, but indeed it should work. I suspect that the socket is not properly closed and reopened when
a "run" section ends. Perhaps @robeme who has recently cleaned up the LAMMPS interface can see to this.

**Comment by robeme** [comment]
Could reproduce the bug and found a solution. init() in the fix class assigns in the second run zero to ipisock due to the if/else construct. I introduced another flag which tells lammps if a socket had been already assigned and check this whenever init() is called.

**Comment by brunoduran** [comment]
Do you have any plan to patch this bug?

I have been following the repo and trying new versions of the software but I cannot see anything done about this.

**Comment by ceriottm** [comment]
It is actually fixed in the latest github versions of LAMMPS - or so should be.

**Comment by robeme** [comment]
It should, but the LAMMPS developers changed something in the domain decomposition balancing. This may have an effect on the i-Pi implementation. Which LAMMPS Version you are currently running?BestRAm 14.03.2017 2:50 nachm. schrieb Michele Ceriotti <notifications@github.com>:It is actually fixed in the latest github versions of LAMMPS - or so should be.

**Comment by brunoduran** [comment]
I thought the problem was within the server. I did not check the commits in the LAMMPS repository. I will pull and compile the last version later this week. 

Thanks for everything,
Bruno

**Comment by ceriottm** [comment]
nono the problem was with LAMMPS.
