### ISSUE TITLE
Removal of i-pi/i-pi github project

### ISSUE THREAD

**Issue by zerothi** [epfl-cosmo/i-pi-dev#161]
Currently when you search for i-pi on github you are most likely to find this:

https://github.com/i-pi/i-pi/graphs/contributors

Do you have any sentiment for keeping the i-pi/i-pi project open? It seems clear that this project site is the main development of i-pi.

Kind regards

**Comment by ceriottm** [comment]
It's a good question -- the idea is that in 2017 we will release a 2.0
version that will go on i-pi/i-pi.
For the moment i-PI is a very young code and so it did make sense to have a
fork in which there were no
guarantees of stability, but I expect things will gradually change and so
yes, ideally i-pi/i-pi should be the
place where the code will go once stable. Also to mark the fact that is not
just a EPFL/COSMO project,
but has contributions from many different places and people.

**Comment by zerothi** [comment]
Ok.

PS. I think the transition should happen before it becomes popular to use
the epfl site. Already now there are many more forks and contributions to
the epfl site.

(Sorry for pushing ;), just my 2 cents)

Thanks!


On 26 Jan 2017 2:47 pm, "Michele Ceriotti" <notifications@github.com> wrote:

It's a good question -- the idea is that in 2017 we will release a 2.0
version that will go on i-pi/i-pi.
For the moment i-PI is a very young code and so it did make sense to have a
fork in which there were no
guarantees of stability, but I expect things will gradually change and so
yes, ideally i-pi/i-pi should be the
place where the code will go once stable. Also to mark the fact that is not
just a EPFL/COSMO project,
but has contributions from many different places and people.


On 26 January 2017 at 07:49, Nick R. Papior <notifications@github.com>
wrote:

> Currently when you search for i-pi on github you are most likely to find
> this:
>
> https://github.com/i-pi/i-pi/graphs/contributors
>
> Do you have any sentiment for keeping the i-pi/i-pi project open? It seems
> clear that this project site is the main development of i-pi.
>
> Kind regards
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/epfl-cosmo/i-pi-dev/issues/161>, or mute the thread
> <https://github.com/notifications/unsubscribe-
auth/ABESZxDBqb-bzOUc2CBE3yR-HlrLL1lVks5rWEHngaJpZM4LuV7Y>
> .
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/epfl-cosmo/i-pi-dev/issues/161#issuecomment-275391718>,
or mute the thread
