### ISSUE TITLE
xyz-file parsing crashes if the file contains one or more blank lines at the end

### ISSUE THREAD

**Issue by ollehellman** [epfl-cosmo/i-pi-dev#165]
Hi,

The title pretty much explains it. Pretty minor issue, but I wasted a few hours on it. Tried to figure out if there was an official standard for it, but could not find anything obvious.

In case this is the expected behavior, perhaps mention in the manual?

**Comment by ceriottm** [comment]
definitely a bug, I/O should be robust enough to handle this - if you could
have a look at it might be an easy way to get into the code, otherwise
@grhawk can probably fix it in 10 minutes

**Comment by grhawk** [comment]
Solved.
